[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.6.3",
    "pynacl>=1.5.0",
    "pytz>=2025.2",
    "youtube-dl>=2021.12.17",
]
